# Generated by Django 3.2 on 2021-07-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_added_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrauntAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[(1, 'Debit'), (2, 'Credit')], max_length=255)),
                ('transaction_amt', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('payment_mode', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestrauntBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_account_no', models.CharField(max_length=255)),
                ('ifsc_no', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companybank',
            name='company_id',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='company_id',
            new_name='restraunt_id',
        ),
        migrations.RenameModel(
            old_name='Company',
            new_name='Restraunt',
        ),
        migrations.DeleteModel(
            name='CompanyAccount',
        ),
        migrations.DeleteModel(
            name='CompanyBank',
        ),
        migrations.AddField(
            model_name='restrauntbank',
            name='restraunt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restraunt'),
        ),
        migrations.AddField(
            model_name='restrauntaccount',
            name='restraunt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restraunt'),
        ),
    ]
